# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Church
  latitude: 34.719930
  longitude: -86.704050
  elevation: 470
  unit_system: imperial
  time_zone: "America/Chicago"
  legacy_templates: false

logger:
  default: info

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zha:
  database_path: /config/zigbee.db
  enable_quirks: true

mqtt:
  discovery: true
  broker: 127.0.0.1
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'

light:
  - platform: mqtt
    schema: json
    name: lutron_qse_nwk
    state_topic: "lutron/qse-nwk"
    command_topic: "lutron/qse-nwk/set"
    brightness: true
    color_mode: true
    supported_color_modes: ["brightness"]
