version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./hass:/config
    environment:
      - TZ=America/Chicago
    restart: always
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_415007C7-if01-port0
    network_mode: host
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: always
    network_mode: host
  zwave-js:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    volumes:
      - ./zwave-js:/usr/src/app/store
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_415007C7-if00-port0
    environment:
      - TZ=America/Chicago
    restart: always
    network_mode: host